# Generated by Django 3.1.7 on 2021-03-30 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_due', models.DateTimeField(null=True)),
                ('priority', models.IntegerField(choices=[(1, 'high'), (2, 'medium-high'), (3, 'medium'), (4, 'medium-low'), (5, 'low')], default=5)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-date_due'],
            },
        ),
    ]
